# Generated by Django 5.1.7 on 2025-03-08 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('enrollment_date', models.DateField()),
                ('expected_graduation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'กำลังศึกษา'), ('leave', 'ลาพัก'), ('graduated', 'จบการศึกษา'), ('terminated', 'พ้นสภาพ')], default='active', max_length=20)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to='advisors.advisor')),
                ('co_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_advised_students', to='advisors.advisor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('TOEFL', 'TOEFL'), ('IELTS', 'IELTS'), ('CU-TEP', 'CU-TEP'), ('TU-GET', 'TU-GET')], max_length=10)),
                ('exam_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pass', 'ผ่าน'), ('fail', 'ไม่ผ่าน')], max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_exam_results', to='students.student')),
            ],
        ),
    ]
