# Generated by Django 5.1.7 on 2025-03-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('submission_date', models.DateField()),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'รอสอบ'), ('passed', 'ผ่าน'), ('passed_with_revision', 'ผ่านโดยมีการแก้ไข'), ('failed', 'ไม่ผ่าน')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_proposal', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisDefense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'รอสอบ'), ('passed', 'ผ่าน'), ('passed_with_revision', 'ผ่านโดยมีการแก้ไข'), ('failed', 'ไม่ผ่าน')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('revision_due_date', models.DateField(blank=True, null=True)),
                ('final_submission_date', models.DateField(blank=True, null=True)),
                ('thesis_proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_defense', to='exams.thesisproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chair', models.BooleanField(default=False)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisors.advisor')),
                ('thesis_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='exams.thesisproposal')),
            ],
            options={
                'unique_together': {('thesis_proposal', 'advisor')},
            },
        ),
    ]
