# Generated by Django 5.1.7 on 2025-03-08 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('degree_type', models.CharField(choices=[('Masters', 'ปริญญาโท'), ('Doctoral', 'ปริญญาเอก')], max_length=20)),
                ('credits_required', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='courses.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_program_chair', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advised_programs', to='advisors.advisor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_advisors', to='courses.program')),
            ],
            options={
                'unique_together': {('program', 'advisor')},
            },
        ),
    ]
