# Generated by Django 5.1.7 on 2025-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_alter_thesis_student_alter_thesis_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='ชื่อวิทยานิพนธ์ (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title_th',
            field=models.CharField(max_length=255, verbose_name='ชื่อวิทยานิพนธ์ (ไทย)'),
        ),
    ]
