# Generated by Django 5.1.7 on 2025-03-27 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_alter_thesis_title_en_alter_thesis_title_th'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
