# Generated by Django 5.1.7 on 2025-03-30 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_user'),
        ('theses', '0005_alter_thesis_advisor_delete_advisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name': 'Thesis', 'verbose_name_plural': 'Theses'},
        ),
        migrations.AlterField(
            model_name='thesis',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_advised_theses', to=settings.AUTH_USER_MODEL, verbose_name='อาจารย์ที่ปรึกษาหลัก'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='students.student'),
        ),
    ]
